from packaging import version

# Get version from file generated by setuptools.
try:
    from ._version import version as __version__
except ImportError:
    # Packaging resources are probably not installed.
    __version__ = '?.?.?'

version_string = f"CoatingGUI {__version__}"

def newer_version(version_str):
    """Check if specified version is newer than the current version."""
    return version_str.parse(version_str) > version.parse(__version__)